config/routes.rb
SmsExample::Application.routes.draw do
  post "sms/update_status" => "sms#update_status"
  get "sms/:id/send_message" => "sms#send_message", :as => :send_message
  get "sms/:id/request_status" => "sms#request_status", :as => :request_status
  resources :sms
  root :to => 'sms#index'
end

app/models/sms.rb
# encoding: utf-8
require "digest"
require 'net/http'
require 'uri'

class Sms < ActiveRecord::Base
  class DeliveryError < Exception
  end
  
  attr_accessible :phone, :subject, :flash, :pl, :localid, :globalid, :status_id, :ok, :sent, :content, :isflash
  after_create :fill_localid
  validates_presence_of :phone, :content
  validates_length_of :content, :maximum => 70
  validates_length_of :phone, :is => 11, :allow_blank => false, :allow_nil => false
  validates_format_of :phone, :with => /\A^48[0-9]+\Z/, :message => "Wrong format of phone number. It should look like 48123123123"

  ERROR_CODES={
    0 => "Brak połączenia z smsc.",
    1 => "Brak autoryzacji, błędny login lub hasło.",
    2 => "Wiadomość została zakolejkowana do wysłania (oczekiwanie na potwierdzenie).",
    3 => "Wiadomość została wysłana do odbiorcy.",
    4 => "Wiadomość odebrana przez odbiorcę (potwierdzenie odbioru).",
    5 => "Błąd wiadomości.",
    6 => "Numer nieaktywny.",
    7 => "Błąd w dostarczeniu wiadomości.",
    8 => "Wiadomość odebrana przez sms center.",
    9 => "Błąd sieci GSM.",
    10 => "Wiadomość wygasła z powodu niemożliwości jej dostarczenia do odbiorcy.",
    11 => "Wiadomość została zakolejkowana do późniejszego wysłania.",
    12 => "Błąd providera, natychmiastowy kontakt z administratorem systemu.",
    103 => "Brak pola text w wiadomości lub pole text niepełne.",
    104 => "Błędnie wypełnione lub brak pola nadawcy.",
    105 => "Pole text jest za długie.",
    106 => "Błędny lub brak pola numer.",
    107 => "Błędny parametr type.",
    110 => "SMSC nie obsługuje danego typu wiadomości.",
    113 => "Pole text jest za długie.",
    201 => "Błąd systemu, natychmiastowy kontakt z administratorem systemu.",
    202 => "Niewystarczająca ilość kredytów na koncie.",
    203 => "Działanie niedozwolone, natychmiastowy kontakt z administratorem systemu.",
    204 => "Konto nieaktywne. Najprawdopodobniej zablokowane.",
    205 => "Sieć docelowa zablokowana.",
    301 => "Brak lub błędny identyfikator wiadomości.",
    500 => "Błędnie wypełnione pole nadawcy lub pole text za długie.",
    600 => "Brak kredytów na koncie premium dla podanego odbiorcy.",
    700 => "Brak potwierdzenia zapisu rekordu.",
    800 => "Deduplikator: Brak Zapisu Rekordu! Wiadomość powtórzona.",
    888 => "Restart zablokowanych smsów.",
    999 => "Zewnętrzna infrastruktura – status przejściowy."
  }

  def self.human_error_code(id)
    ERROR_CODES[id]
  end

  def status
      Sms.human_error_code self.status_id
  end

  def fill_localid
    self.update_attribute(:localid, self.created_at.to_i)
  end

  def status
    Sms.human_error_code self.status_id
  end

  def request_status
    url = URI.parse(APP_CONFIG["gatesms"]["send_url"])
    request = Net::HTTP::Post.new(url.path)
    request.body = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><report>
    <status timestamp="'+self.created_at.to_i.to_s+'" ok="true" globalid="'+self.globalid.to_s+'"/></report>'
    hash_body = Digest::MD5.hexdigest(request.body)
    hash = Digest::MD5.hexdigest("POST/sms_xmlapi.php#{hash_body}Accept:application/xml#{self.created_at.to_i.to_s}#{APP_CONFIG["gatesms"]["SecretKey"]}")
    request["X-GT-Auth"] = "#{APP_CONFIG["gatesms"]["KeyId"]}:" + hash
    request["X-GT-Timestamp"] = self.created_at.to_i.to_s
    request["Content-Type"] = "application/x-www-form-urlencoded"
    request["Accept"] = "application/xml"
    request["Expect"] = "100-continue"
    request["X-GT-Action"] = "GET STATUS"
    request.body="body=#{ERB::Util.url_encode(request.body)}"

    http = Net::HTTP.new(url.host, url.port)
    response = http.request(request)
    @html = Nokogiri::HTML(response.body)
    @html.search('status').each do |value|
      @status = value
    end
    if @status[:localid].to_i == self.localid
      self.update_attributes(:status_id=>@status.content.to_i, :globalid=>@status[:globalid].to_i, :sent=>@status[:ok].to_boolean)
    end
  end

  def send_message
    url = URI.parse(APP_CONFIG["gatesms"]["send_url"])
    request = Net::HTTP::Post.new(url.path)
    request.body = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><package test="'+APP_CONFIG["gatesms"]["test"].to_s+'">
    <msg pl="true" phone="'+self.phone+'" localid="'+self.localid.to_s+'" isflash="'+self.isflash.to_s+'" from="BrainBox">'+self.content.to_s+'</msg></package>'
    hash_body = Digest::MD5.hexdigest(request.body)
    hash = Digest::MD5.hexdigest("POST/sms_xmlapi.php#{hash_body}Accept:application/xml#{self.created_at.to_i.to_s}#{APP_CONFIG["gatesms"]["SecretKey"]}")
    request["X-GT-Auth"] = "#{APP_CONFIG["gatesms"]["KeyId"]}:" + hash
    request["X-GT-Timestamp"] = self.created_at.to_i.to_s
    request["Content-Type"] = "application/x-www-form-urlencoded"
    request["Accept"] = "application/xml"
    request["Expect"] = "100-continue"
    request.body="body=#{ERB::Util.url_encode(request.body)}"

    http = Net::HTTP.new(url.host, url.port)
    #http.set_debug_output $stderr
    response = http.request(request)
    @html = Nokogiri::HTML(response.body)
    @html.search('status').each do |value|
      @status = value
    end
    if @status[:localid].to_i == self.localid
      self.update_attributes(:status_id=>@status.content.to_i, :globalid=>@status[:globalid].to_i, :ok=>@status[:ok].to_boolean, :sent=>true)
    end
    
    raise DeliveryError unless [2, 3, 4].include?(@status.content.to_i)
  end

end

app/controllers/sms_controller.rb
# encoding: utf-8
require "digest"

class SmsController < ApplicationController
  layout false, :only => :update_status
  protect_from_forgery :except => :update_status

  def update_status
    @sms = Sms.find_by_localid(params[:LocalId].to_i)
    if @sms and @sms.globalid == params[:Id].to_i
      update = @sms.update_attributes(:status_id=>params[:Status].to_i)
    end
    #for header in request.env.select {|k,v| k.match("^X.*") }
    #  p header.inspect
    #end
    if update
      render :text => "ok", :status => 204
    else
      render :text => "continue", :status => 202
    end
  end

  # GET /sms
  # GET /sms.json
  def index
    @sms = Sms.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sms }
    end
  end

  # GET /sms/1
  # GET /sms/1.json
  def show
    @sms = Sms.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sms }
    end
  end

  # GET /sms/new
  # GET /sms/new.json
  def new
    @sms = Sms.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sms }
    end
  end

  # GET /sms/1/edit
  def edit
    @sms = Sms.find(params[:id])
  end

  # POST /sms
  # POST /sms.json
  def create
    @sms = Sms.new(params[:sms])

    respond_to do |format|
      if @sms.save
        format.html { redirect_to @sms, notice: 'Sms was successfully created.' }
        format.json { render json: @sms, status: :created, location: @sms }
      else
        format.html { render action: "new" }
        format.json { render json: @sms.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sms/1
  # PUT /sms/1.json
  def update
    @sms = Sms.find(params[:id])

    respond_to do |format|
      if @sms.update_attributes(params[:sms])
        format.html { redirect_to @sms, notice: 'Sms was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sms.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sms/1
  # DELETE /sms/1.json
  def destroy
    @sms = Sms.find(params[:id])
    @sms.destroy

    respond_to do |format|
      format.html { redirect_to sms_index_url }
      format.json { head :no_content }
    end
  end

  def send_message
    @sms = Sms.find(params[:id])
    @sms.send_message
    render :show
  end

  def request_status
    @sms = Sms.find(params[:id])
    @sms.send_message
    render :show
  end
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/sms/_form.html.erb
<%= form_for @sms, :html => { :class => 'form-horizontal' } do |f| %>
  <%= errors_for(@sms, "Can't create SMS.").html_safe %>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :isflash, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :isflash, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pl, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :pl, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sms/edit.html.erb
<%- model_class = @sms.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sms/index.html.erb
<%- model_class = Sms.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:isflash) %></th>
      <th><%= model_class.human_attribute_name(:pl) %></th>
      <th><%= model_class.human_attribute_name(:globalid) %></th>
      <th><%= model_class.human_attribute_name(:localid) %></th>
      <th><%= model_class.human_attribute_name(:status_id) %></th>
      <th><%= model_class.human_attribute_name(:ok) %></th>
      <th><%= model_class.human_attribute_name(:sent) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sms.each do |sms| %>
      <tr>
        <td><%= link_to sms.id, sms_path(sms) %></td>
        <td><%= sms.phone %></td>
        <td><%= sms.subject %></td>
        <td><%= sms.content %></td>
        <td><%= sms.isflash %></td>
        <td><%= sms.pl %></td>
        <td><%= sms.globalid %></td>
        <td><%= sms.localid %></td>
        <td><%= sms.status_id %></td>
        <td><%= sms.ok %></td>
        <td><%= sms.sent %></td>
        <td><%=l sms.created_at %></td>
        <td>
          <% unless sms.sent? %><%= link_to t('.send', :default => t("helpers.links.send")),
                      send_message_path(sms), :class => 'btn btn-mini btn-warning' %>
          <% else %>
              <%= link_to t('.request_status', :default => t("helpers.links.request_status")),
                                  request_status_path(sms), :class => 'btn btn-mini btn-primary' %>
          <% end %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sms_path(sms), :class => 'btn btn-mini' %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      sms_path(sms), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sms_path(sms),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sms_path,
            :class => 'btn btn-primary' %>

app/views/sms/new.html.erb
<%- model_class = @sms.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sms/show.html.erb
<%- model_class = @sms.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @sms.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @sms.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @sms.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isflash) %>:</strong></dt>
  <dd><%= @sms.isflash %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pl) %>:</strong></dt>
  <dd><%= @sms.pl %></dd>
  <% if @sms.globalid %><dt><strong><%= model_class.human_attribute_name(:globalid) %>:</strong></dt>
  <dd><%= @sms.globalid %></dd><% end %>
  <dt><strong><%= model_class.human_attribute_name(:localid) %>:</strong></dt>
  <dd><%= @sms.localid %></dd>
  <% if @sms.status_id %>
  <dt><strong><%= model_class.human_attribute_name(:status_id) %>:</strong></dt>
  <dd><%= @sms.status_id %>: <%= @sms.status %></dd><% end %>
  <dt><strong><%= model_class.human_attribute_name(:ok) %>:</strong></dt>
  <dd><%= @sms.ok %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sent) %>:</strong></dt>
  <dd><%= @sms.sent %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sms_path(@sms), :class => 'btn' %>
  <% unless @sms.sent? %><%= link_to t('.send', :default => t("helpers.links.send")),
              send_message_path(@sms), :class => 'btn btn-warning' %>
  <% else %>
      <%= link_to t('.request_status', :default => t("helpers.links.request_status")),
                    request_status_path(@sms), :class => 'btn btn-primary' %>
  <% end %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sms_path(@sms),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>